package com.plr.comparator.alphanum
/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'plr' at '4/23/16 9:04 PM' with Gradle 2.12
 *
 * @author plr, @date 4/23/16 9:04 PM
 */

import static com.plr.comparator.alphanum.CompType.*
import spock.lang.Specification
import static com.plr.comparator.alphanum.NaturalComparator.Flags.*


class IgnoreSpaceTest extends Specification {



	def "Pure numbers comparison equal"() {

		given:

		expect:


		AlphaTokenComparable.compareSpaceInsensitve(smaller, bigger) == 0;

		where:

		smaller 		| bigger
		"a"			| "a"
		"abc"	| "abc"
		"a"			| "a "
		"a "			| "a"
		"abc"	| "abc "
		"a"			| " a "
		"abc"	| " a b   c "
		"  \n   abc  \n"	| " a b   c "
		" "	| ""
		""	| "\n"
	}

	def "Pure numbers comparison smaller"() {

		given:

		expect:

		AlphaTokenComparable.compareSpaceInsensitve(smaller, bigger) < 0;
		AlphaTokenComparable.compareSpaceInsensitve(bigger, smaller) > 0;

		where:

		smaller 		| bigger
		"a"			| "b"
		"ab"		| "abc"
		" ab"		| "abc"
		" a  b "	| "abc"
	}

	def "Pure numbers comparison equal2"() {

		given:

		expect:


		AlphaTokenComparable.compareSpaceInsensitve2(smaller, bigger) == 0;

		where:

		smaller 		| bigger
//		"a"			| "a"
//		"abc"	| "abc"
//		"ab c"	| "ab   c"
		"b "			| "b\n\n"
//		"abc"	| "abc "
//		"   a "			| " a          "
//		" "	| "\n\n\n\n\n\n\n\n"
//		""	| ""
	}
	
	def "Pure numbers comparison smaller2"() {

		given:

		expect:

		AlphaTokenComparable.compareSpaceInsensitve2(smaller, bigger) < 0;
		AlphaTokenComparable.compareSpaceInsensitve2(bigger, smaller) > 0;

		where:

		smaller 		| bigger
		"a"			| "a "
		" c"			| "c"
		"d "			| "d    g"

	}
}
