package com.plr.comparator.alphanum
/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'plr' at '4/23/16 9:04 PM' with Gradle 2.12
 *
 * @author plr, @date 4/23/16 9:04 PM
 */

import spock.lang.Specification
import static com.plr.comparator.alphanum.CompType.*

class NaturalComparatorTest extends Specification {




	def "Mutiple cases of parser"() {

		given:
		NaturalComparator naturalComparator = new NaturalComparator();
		
		
		def list = naturalComparator.split(first)
		
		def list2 = []
		
		list.each { token ->
			list2 << token.getStr()
		}

		println "$first -> $list"

		expect:



		list2 == expected


		where:

		first 				| expected 		
		"doc20.doc" 		| ["doc", "20", ".doc" ] 	
		"doc10.doc"			| ["doc", "10", ".doc" ] 
		"doc2.doc"			| ["doc", "2", ".doc" ] 	
		"doc2.1.doc"		| ["doc", "2.1", ".doc" ] 	
		"doc2.10.doc"		| ["doc", "2.10", ".doc" ] 	
		
		//pure numbers
		"20"				| ["20"]	
		"2"					| ["2"]
		"-20"				| ["-20"]
		" -40"				| [" -40"]
		"-20.234"			| ["-20.234"]
		
		//comma or hyphen in string
		"asdf-20.234"		| ["asdf-", "20.234"]
		"asdf-20.234asdf"	| ["asdf-", "20.234", "asdf"]
		"TEST20.23.4.8asdf"	| ["TEST", "20", ".", "23", ".", "4.8", "asdf"]
		"TEST20-23-4-8asdf"	| ["TEST", "20", "-", "23", "-", "4", "-", "8", "asdf"]
		
		//zeros
		"03.50"				| ["03.50"]
		"00003"				| ["00003"]
		"0.3000"			| ["0.3000"]
		
		//spaces
		"pics 5"			| ["pics", " 5"]
		"pics    5"			| ["pics", "    5"]
		"pics 5 test"		| ["pics", " 5", " test"]
		"pics    5 6"		| ["pics", "    5", " 6"]
	}

	def "Pure numbers" () {
		given:
		NaturalComparator naturalComparator = new NaturalComparator();
		
		def expected = ["-123", "-12",
			"-1.1532456", "-1.15", "-1.1" , "-1", "-0.99999999999", "-0.99",
			"-0.15", "-0.1",  "0", "0.1", "0.15", "1",  "1.1", "1.15",
			"11.1", "11.67", "11.6756745674", "11.68", "12", "123"]
		
		def list = []
		
		list.addAll(expected)

		Collections.shuffle(list)

		when: "Do nothing"

		then: "The list aren't equal"
		list != expected

		when: "Sorting list"
		Collections.sort(list, naturalComparator)

		then: "The list are equal"
		
		println list
		println expected
		
		for(int i = 0; i < list.size(); i++) {
			list[i] == expected[i]
		}
		
		list == expected
	}
	
	def "Pure numbers comparaizon"() {
		
				given:
				NaturalComparator naturalComparator = new NaturalComparator();
		
				expect:
		
				naturalComparator.compare(smaller, bigger) < 0
				naturalComparator.compare(bigger , smaller) > 0
		
				where:
		
				smaller 		| bigger 		
				"-123"			| "-1.15" 
				"-1.1532456"	| "-1.15"
				"123"			| "1234"
				"-1.1532456"	| "-1"
				
			}
	
	
	def "test sort list" () {
		given:
		NaturalComparator naturalComparator = new NaturalComparator();


		def list = [
			"z1.doc",
			"z10.doc",
			"z100.doc",
			"z101.doc",
			"z102.doc",
			"z11.doc",
			"z12.doc",
			"z13.doc",
			"z14.doc",
			"z15.doc",
			"z16.doc",
			"z17.doc",
			"z18.doc",
			"z19.doc",
			"z2.doc",
			"z20.doc",
			"z3.doc",
			"z4.doc",
			"z5.doc",
			"z6.doc",
			"z7.doc",
			"z8.doc",
			"z9.doc",
		]

		def expected = [
			"z1.doc",
			"z2.doc",
			"z3.doc",
			"z4.doc",
			"z5.doc",
			"z6.doc",
			"z7.doc",
			"z8.doc",
			"z9.doc",
			"z10.doc",
			"z11.doc",
			"z12.doc",
			"z13.doc",
			"z14.doc",
			"z15.doc",
			"z16.doc",
			"z17.doc",
			"z18.doc",
			"z19.doc",
			"z20.doc",
			"z100.doc",
			"z101.doc",
			"z102.doc",
		]



		when: "Do nothing"

		then: "The list aren't equal"
		list != expected

		when: "Sorting list"
		
		println list
		Collections.sort(list, naturalComparator)
		println list
		
		then: "The list are equal"
		list == expected
	}


	def "product names sort"() {
		given:

		NaturalComparator naturalComparator = new NaturalComparator();

		def list = [
			"1000X Radonius Maximus",
			"10X Radonius",
			"200X Radonius",
			"20X Radonius",
			"20X Radonius Prime",
			"30X Radonius",
			"40X Radonius",
			"Allegia 50 Clasteron",
			"Allegia 500 Clasteron",
			"Allegia 50B Clasteron",
			"Allegia 51 Clasteron",
			"Allegia 6R Clasteron",
			"Alpha 100",
			"Alpha 2",
			"Alpha 200",
			"Alpha 2A",
			"Alpha 2A-8000",
			"Alpha 2A-900",
			"Callisto Morphamax",
			"Callisto Morphamax 500",
			"Callisto Morphamax 5000",
			"Callisto Morphamax 600",
			"Callisto Morphamax 6000 SE",
			"Callisto Morphamax 6000 SE2",
			"Callisto Morphamax 700",
			"Callisto Morphamax 7000",
			"Xiph Xlater 10000",
			"Xiph Xlater 2000",
			"Xiph Xlater 300",
			"Xiph Xlater 40",
			"Xiph Xlater 5",
			"Xiph Xlater 50",
			"Xiph Xlater 500",
			"Xiph Xlater 5000",
			"Xiph Xlater 58"
		]

		def expected = [
			"10X Radonius",
			"20X Radonius",
			"20X Radonius Prime",
			"30X Radonius",
			"40X Radonius",
			"200X Radonius",
			"1000X Radonius Maximus",
			"Allegia 6R Clasteron",
			"Allegia 50 Clasteron",
			"Allegia 50B Clasteron",
			"Allegia 51 Clasteron",
			"Allegia 500 Clasteron",
			"Alpha 2",
			"Alpha 2A",
			"Alpha 2A-900",
			"Alpha 2A-8000",
			"Alpha 100",
			"Alpha 200",
			"Callisto Morphamax",
			"Callisto Morphamax 500",
			"Callisto Morphamax 600",
			"Callisto Morphamax 700",
			"Callisto Morphamax 5000",
			"Callisto Morphamax 6000 SE",
			"Callisto Morphamax 6000 SE2",
			"Callisto Morphamax 7000",
			"Xiph Xlater 5",
			"Xiph Xlater 40",
			"Xiph Xlater 50",
			"Xiph Xlater 58",
			"Xiph Xlater 300",
			"Xiph Xlater 500",
			"Xiph Xlater 2000",
			"Xiph Xlater 5000",
			"Xiph Xlater 10000"
		]
	
		when: "Do nothing"

		then: "The list aren't equal"
		list != expected

		when: "Sorting list"
		Collections.sort(list, naturalComparator)

		then: "The list are equal"
		list == expected
	}

	def "Mutiple cases sdfa"() {

		given:
		NaturalComparator naturalComparator = new NaturalComparator();
		def expected = [
			"1-2",
			"1-02",
			"1-20",
			"10-20",
			"fred",
			"jane",
			"pic01",
			"pic2",
			"pic02",
			"pic02a",
			"pic3",
			"pic4",
			"pic 4 else",
			"pic 5",
			"pic 5",
			"pic05",
			"pic 5 something",
			"pic 6",
			"pic   7",
			"pic100",
			"pic100a",
			"pic120",
			"pic121",
			"pic02000",
			"tom",
			"x2-g8",
			"x2-y7",
			"x2-y08",
			"x8-y8"
		]


		def list = []

		list.addAll(expected)


		Collections.shuffle(list)

		when: "Do nothing"

		then: "The list aren't equal"
		list != expected

		when: "Sorting list"
		Collections.sort(list, naturalComparator)

		then: "The list are equal"
		
		println "Sorted:   " + list
		println "Expected: " + expected
		
		for(int i = 0; i < list.size(); i++) {
			list[i] == expected[i]
		}
		
		list == expected
	}

	boolean compToZero(NaturalComparator naturalComparator, CharSequence s1, CharSequence s2, CompType compType) {

		int val = naturalComparator.compare(s1, s2)

		switch (compType) {
			case GREATER:
				return val > 0
			case LESS:
				return val < 0
			case EQUAL:
				return val == 0
		}
	}

	def "Mutiple cases"() {

		given:
		NaturalComparator naturalComparator = new NaturalComparator();

		expect:

		compToZero (naturalComparator, first, second, comparison) == true

		where:

		first 			| second 		| comparison
		"doc20.doc" 	| "doc10.doc" 	| GREATER
		"doc10.doc"		| "doc20.doc" 	| LESS
		"doc2.doc"		| "doc10.doc" 	| LESS
		"doc2.1.doc"	| "doc2.2.doc"	| LESS
		"doc2.10.doc"	| "doc2.2.doc"	| LESS
		"20"			| "10"			| GREATER
		"2"				| "10"			| LESS
		"-20"			| "10"			| LESS
		"-20"			| "-10"			| LESS
		"pic05"			| "pic 5"		| GREATER
		"pic02000"		| "pic2"		| GREATER
		"1-2"			| "1-02"		| LESS
	}
	
	def "Mutiple cases2"() {
	
		
		given:
		NaturalComparator naturalComparator = new NaturalComparator();

		expect:

		compToZero (naturalComparator, "z1.doc", "z11.doc", LESS) == true
		compToZero (naturalComparator, "z11.doc", "z1.doc", GREATER) == true
		
		compToZero (naturalComparator, "z1.doc", "z11.doc", GREATER) == false
		compToZero (naturalComparator, "z11.doc", "z1.doc", LESS) == false
		
		
		compToZero (naturalComparator, "z10.doc", "z11.doc", LESS) == true
		compToZero (naturalComparator, "z11.doc", "z10.doc", GREATER) == true

	}
	
	def "Mutiple cases3"() {


		given:
		NaturalComparator naturalComparator = new NaturalComparator();

		//			def s1 = "Alpha 2A-8000"
		//			def s2 = "Alpha 2A-900"

		def s1 = "1-2"
		def s2 = "1-02"

		int val = naturalComparator.compare(s1, s2);

		println "The val: $val"

		println "s1: " + naturalComparator.split(s1)

		println "s2: " +  naturalComparator.split(s2)



		NumberTokenComparable nt1 = new NumberTokenComparable(smaller, NaturalComparator.ASCII);
		NumberTokenComparable nt2 = new NumberTokenComparable(bigger, NaturalComparator.ASCII);

		expect:

		nt1.compareTo(nt2) < 0
		nt2.compareTo(nt1) > 0


		where:

		smaller		|	bigger
		"10"		| "11"
		"10.12"		| "10.123"
		"-10.12"	| "10.123"
		"-10.123"	| "-10.12"
		"-10.123"	| "10.12"
	}
}
